alias 2screen='xrandr --output HDMI-1-0 --auto --right-of eDP-1'
alias multt='kitty +kitten broadcast'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias vi='nvim'
alias r='ranger'
